INSERT INTO dogs (id, name, trait) VALUES ("1", "Labrador Retriever", "Friendly, loyal and ready to retrieve birds on the hunt or fetch for hours!");
INSERT INTO dogs (id, name, trait) VALUES ("2", "German Shepherd", "Smart, alert and protective. This pup is ready to protect the pack!");
INSERT INTO dogs (id, name, trait) VALUES ("3", "Golden Retriever", "The quintessential family dog! Friendly, goofy and easy going.");
INSERT INTO dogs (id, name, trait) VALUES ("4", "French Bulldog", "The class-clown! This goof ball is easy going and a great family pet.");
INSERT INTO dogs (id, name, trait) VALUES ("5", "English Bulldog", "Our favorite mascot dog! This pup is a couch potato with a personality.");
INSERT INTO dogs (id, name, trait) VALUES ("6", "Standard Poodle", "Our valedictorian dog! Be ready to keep this pup stimulated with exercise and tricks.");
INSERT INTO dogs (id, name, trait) VALUES ("7", "Beagle", "A real howler! Beagles have big personality, a strong nose for the hunt but chill with the family.");
INSERT INTO dogs (id, name, trait) VALUES ("8", "Rottweiler", "A workhorse pup! Rottweilers need a job, be ready to offer jobs and direction for this pup.");
INSERT INTO dogs (id, name, trait) VALUES ("9", "German Shorthaired Pointer", "An alert spy! This pup is loyal and alert and ready to show you the way towards game.");
INSERT INTO dogs (id, name, trait) VALUES ("10", "Pembroke Welsh Corgi", "The Queen's dog! These high energy goofballs are very adaptable. ");
INSERT INTO dogs (id, name, trait) VALUES ("11", "Dachshund", "A big personality in a little package! These pups are curious, a bit independent and ready for the hunt!");
INSERT INTO dogs (id, name, trait) VALUES ("12", "Yorkshire Terrier", "A true terrier! This pup is feisty and sweet.");
INSERT INTO dogs (id, name, trait) VALUES ("13", "Australian Shepherd", "Work, work work! This pup is ready to herd the flock, fetch the ball or whatever task you hand it!");
INSERT INTO dogs (id, name, trait) VALUES ("14", "Boxer", "A playful pup! This dog is sweet, goofy and inquisitive");
INSERT INTO dogs (id, name, trait) VALUES ("15", "Siberian Husky", "Ready for the iditerod! This sledding pup is independent and loves a job. Best suited for a cold climate.");
INSERT INTO dogs (id, name, trait) VALUES ("16", "Cavalier King Charles Spaniel", "True royalty! This dog is sweet as pie and ready to warm any lap available.");
INSERT INTO dogs (id, name, trait) VALUES ("17", "Great Dane", "Make way! This pup is goofy, huge, loving and mistakenly thinks your lap is an option. ");
INSERT INTO dogs (id, name, trait) VALUES ("18", "Miniature Schnauzer", "Smart, friendly and eager to please!");
INSERT INTO dogs (id, name, trait) VALUES ("19", "Doberman Pinscher", "As loyal as they come! This pup is ready to protect the pack, always alert and fearless.");
INSERT INTO dogs (id, name, trait) VALUES ("20", "Shih Tzu", "A true family pet! Easy with children, playful and sweet");
INSERT INTO dogs (id, name, trait) VALUES ("21", "Boston Terrier", "Endlessly entertaining! A great apartment pet with playful energy.");
INSERT INTO dogs (id, name, trait) VALUES ("22", "Havanese", "Alert but quiet, these playful pups are ready to be trained!");
INSERT INTO dogs (id, name, trait) VALUES ("23", "Bernese Mountain Dog", "Gentle giant! This pup is a great family pet if you can handle a bit of slobber.");
INSERT INTO dogs (id, name, trait) VALUES ("24", "Pomeranian", "Tiny with big personality! This pup is ready to play all day");
INSERT INTO dogs (id, name, trait) VALUES ("25", "Shetland Sheepdog", "Oh Lassie! This movie star pup is sweet and ready to be put to work. If you can handle the shedding!");
